### ISSUE TITLE
[Suggestion] Toggle to change 24-hour clock to 12-hour clock

### ISSUE THREAD

**Issue by Mr-Foxtrot** [notsapinho/day-night-powercord#1]
I suggest there should be an option to change the format in the "Enable time in status" setting from the 24-hour clock to 12-hour clock. That way people can pick between which format they prefer.

**Comment by notsapinho** [comment]
Thanks for the suggestion, it will be added in the new version!

**Comment by Mr-Foxtrot** [comment]
Sweet!
