### ISSUE TITLE
Powercord reloads when selecting enable time in status

### ISSUE THREAD

**Issue by BCI1999** [notsapinho/day-night-powercord#2]
Everytime I try to turn on or off the "Enable time in status" function, Powercord automatically reloads.
This didn't happen before, so I guess this plugin has to be updated?

**Comment by notsapinho** [comment]
Did you renamed your folder?

**Comment by BCI1999** [comment]
I already tried to update it with the latest version, and all my other plugins work fine. Reinstalling Powercord didn't help either

**Comment by notsapinho** [comment]
what's your plugin folder named

**Comment by BCI1999** [comment]
Just the default "plugins" name

**Comment by notsapinho** [comment]
no no, the day night plugin folder

**Comment by BCI1999** [comment]
Ooh, alright, that one is named "day-night-powercord"

**Comment by notsapinho** [comment]
alright so its correct, i can think of any problems, mine is working

**Comment by BCI1999** [comment]
That's odd, I'll try some things again maybe I missed something

**Comment by notsapinho** [comment]
add me on discord so we can talk better

**Comment by BCI1999** [comment]
Latest update fixed this, thanks again!!
