### ISSUE TITLE
Animated status plugin

### ISSUE THREAD

**Issue by itsmeboy0** [notsapinho/day-night-powercord#3]
Thanks for this plugin.

Since this is close to an animated status plugin, would there be a chance you would create one?

Thanks in advance.

**Comment by notsapinho** [comment]
Can you explain me a little more?

**Comment by itsmeboy0** [comment]
> Can you explain me a little more?

Can you create an animated status plugin instead [like this one](https://github.com/toluschr/BetterDiscord-Animated-Status) as the plugin can do the same thing anyway, with other customizations.

**Comment by notsapinho** [comment]
I will be taking a look thanks for the suggestion!

**Comment by notsapinho** [comment]
https://github.com/notsapinho/powercord-animated-status

Done!
